// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mentor_assistant/features/settings/data/models/cycle_config_model.dart';
import 'package:mentor_assistant/features/settings/data/models/group_config_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CycleConfigModelAdapter());
    registerAdapter(GroupConfigModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CycleConfigModelAdapter());
    registerAdapter(GroupConfigModelAdapter());
  }
}
